name: 🚀 Tarea de Despliegue

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🎉 Trabajo de Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obteniendo el código más reciente
        uses: actions/checkout@v4

      - name: 🛠️ Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Buscamos el lock en la subcarpeta
          cache-dependency-path: 'CosmicCollector/package-lock.json'

      - name: 📦 Instalando dependencias
        working-directory: ./CosmicCollector # <--- Entramos en la carpeta
        run: npm install

      - name: 🏗️ Construyendo la aplicación
        working-directory: ./CosmicCollector # <--- Entramos en la carpeta
        run: npm run build

      - name: 📂 Sincronizando archivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-repoclase.alwaysdata.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./CosmicCollector/dist/ # <--- Subimos la dist de la carpeta
          server-dir: www/
          protocol: ftps
          timeout: 86400000
          log-level: standard
          exclude: |
            .git/**
            .github/**
            node_modules/**